--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/thebigsmileXD/Backpack
projects:
  Backpack:
    path: ""
    icon: "resources/github/backpack.png"
    excludeDirs:
    - "resources/github"
    libs:
    - src: CortexPE/Commando/Commando
      version: ^0.3.1
...
